### PR TITLE
new offset?

### PR DESCRIPTION
**Pull request by NekoRem**
not sure if this is correct but there was a patch for apex. this is what my dumper gave me

### CODE REVIEW

**Comment by UrAvgCoder** [comment]
Thanks for the push, mind linking me to your dumper? I would love to learn about that ;)

**Comment by NekoRem** [comment]
> Thanks for the push, mind linking me to your dumper? I would love to learn about that ;)

i do mind. make your own. And no stop lying to me and yourself you don't want to learn from it you just want to help your little paste project

**Comment by UrAvgCoder** [comment]
ouch, that's a bit harsh statement, I've been learning also pushed a small typo in this repo under glow, but hey if you think that way, good ;)

**Comment by NekoRem** [comment]
> ouch, that's a bit harsh statement, I've been learning also pushed a small typo in this repo under glow, but hey if you think that way, good ;)

i never made that typo and i noticed it within 5 minutes of looking at the source for the first time. And don't act smart. boy...

**Pull request merged**
